var str = "Length of a short string ";
var num = 300;

print ("string: '", str, "'");
print ("length: ", "'", str.length, "'");
print ("charAt 2: ", "'", str.charAt(2), "'");
print ("concat a,2,3: ", "'", str.concat(str, "a",2,3), "'");
print ("endsWith 9: ", "'", str.endsWith("g"), "'");
print ("includes th: ", "'", str.includes("th"), "'");
print ("includes tx: ", "'", str.includes("tx"), "'");
print ("indexOf th: ", "'", str.indexOf("th"), "'");
print ("lastIndexOf g: ", "'", str.lastIndexOf("g"), "'");
print ("replaceAll g w/xx: ", "'", str.replaceAll("g", "xx"), "'");
print ("replace g w/xx: ", "'", str.replace("g", "xx"), "'");
print ("slice 1: ", "'", str.slice(1), "'");
print ("slice -4: ", "'", str.slice(-4), "'");
print ("split: ", "'", str.split(" "), "'");
print ("startsWith of: ", "'", str.startsWith("of", 7), "'");
print ("startsWith of: ", "'", str.startsWith("of", 6), "'");
print ("substr 6: ", "'", str.substr(6), "'");
print ("substr 6,3: ", "'", str.substr(6, 3), "'");
print ("subString 6: ", "'", str.substring(6), "'");
print ("toLowerCast: ", "'", str.toLowerCase(), "'");
print ("toUpperCase: ", "'", str.toUpperCase(), "'");
print ("trim: ", "'", str.trim(), "'");
print ("toExponential 300: ", "'", num.toExponential(2), "'");
print ("toString 300: ", "'", num.toString(), "'");
